version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: docatl
archives:
  - formats: ['binary']
dockers:
  - dockerfile: "Dockerfile"
    image_templates:
      - ghcr.io/docat-org/docatl:latest
      - ghcr.io/docat-org/docatl:{{ .Tag }}
      - ghcr.io/docat-org/docatl:{{ .Major }}
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - pkg/
      - internal/
  - dockerfile: "Dockerfile.alpine"
    image_templates:
      - ghcr.io/docat-org/docatl:latest-alpine
      - ghcr.io/docat-org/docatl:{{ .Tag }}-alpine
      - ghcr.io/docat-org/docatl:{{ .Major }}-alpine
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - pkg/
      - internal/
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
