FROM golang:1.19-alpine AS build
WORKDIR /src
COPY . /src/
RUN CGO_ENABLED=0 go build -o /bin/docatl

FROM alpine:latest
RUN apk update \
    && apk add -U --no-cache ca-certificates zip
COPY --from=build /bin/docatl /bin/docatl
WORKDIR /docs
CMD [ "/bin/docatl" ]
