FROM golang:1.17-alpine AS build
WORKDIR /src
COPY . /src/
RUN CGO_ENABLED=0 go build -o /bin/docatl

FROM alpine:latest
COPY --from=build /bin/docatl /bin/docatl
WORKDIR /docs
ENTRYPOINT [ "/bin/docatl" ]